default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  

development:
  <<: *default
  database: todo-app_development
  password: password

test:
  <<: *default
  database: todo-app_test
  password: password

production:
  <<: *default
  databese: todo-app_production
  username: todo-app
  password: <%= ENV['TODO-APP_DATABASE_PASSWORD'] %>
