
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: todo-app_development

test:
  <<: *default
  database: todo-app_test

production:
  <<: *default
  databese: todo-app
  username: todo-app
  password: <%= ENV['appname_DATABASE_PASSWORD'] %>